# Generated by Django 2.2.17 on 2020-12-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://designshack.net/wp-content/uploads/placeholder-image-368x246.png', max_length=500),
        ),
    ]
