# Generated by Django 2.2.17 on 2020-12-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_allowed_people',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='item',
            name='item_opening_hours',
            field=models.CharField(default='07:00', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='item_sales',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='item_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
