# Generated by Django 2.2.17 on 2020-12-31 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_item_item_people_inside'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_price',
        ),
    ]
