# Generated by Django 2.2.17 on 2021-01-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_item_item_shipping_avail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_allowed_people',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_people_inside',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
