# Generated by Django 2.2.17 on 2021-01-01 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20210101_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_shipping_avail',
            new_name='item_shipping_available',
        ),
    ]
