# Generated by Django 2.2.17 on 2021-01-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_item_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_opening_hours',
            field=models.CharField(default='07:00-21:00', max_length=12),
        ),
    ]
